### ISSUE TITLE
Rapidly pressing Start/Pause buttons also activates the settings after the appropriate number of presses

### ISSUE THREAD

**Issue by TheIronMarx** [msimonides/homerplayer#1]
Trying to rewind the audiobook back several seconds, I smashed the start and pause buttons to spam the rewind feature. Turns out, the button is included with the clickable View which displays the settings page. I propose the button is excluded from that clickable region which opens the settings -- it already has given functionality. The settings which opens is jarring.

**Comment by msimonides** [comment]
Thanks for the report. I'm aware of this issue and intend to fix it.

Note: more importantly, I plan to add a "proper" rewind functionality.

**Comment by TheIronMarx** [comment]
I'd love to help, if you're interested. If you would make an issue for it, we could talk about it there. Glad to hear rewind functionality is on the list.
