### ISSUE TITLE
New release increased number of trackers to 4

### ISSUE THREAD

**Issue by IzzySoft** [msimonides/homerplayer#20]
I just saw your new release today, and unfortunately you've increased the number of non-FOSS trackers to 4 (GMS, Firebase, Firebase Analytics, Crashlytics). Could you please reconsider that decision? Crashlytics is discontinued anyway, so it could certainly be removed. If you need crash reports etc., there are other, FOSS solutions for that ([ACRA](https://github.com/ACRA/acra), [tracedroid](https://github.com/ligi/tracedroid) and more) – so you could even make the app completely FOSS when leaving GMS and Firebase out.

Thanks for considering!

**Comment by msimonides** [comment]
Actually the only change was to switch from Flurry Analytics to Firebase Analytics, so the number of services getting the data should be the same. Unless I'm missing something.
Analytics is currently running with GAID and SSID tracking disabled, so privacy-wise it's probably better than before (though I'm not an expert on this).
This app has been using Crashlytics for years now, nothing has changed here (though the account is now switched over to Firebase).

May I ask what would be the gain of switching to FOSS solutions?
I do need to gather crash reports and would like to have some basic analytics. The data needs to reside somewhere on some servers operated by a 3rd party company (preferably free).

**Comment by IzzySoft** [comment]
Thanks for your reply, @msimonides! And apologies for the initial confusion: I just got an alert from my updater that there were additional trackers – and only noticed lateron that some of them were already present in previous versions.

> May I ask what would be the gain of switching to FOSS solutions?

I gladly explain that! First, it would mean that less data (including PII) would go to Google. Second it would mean that you could *exactly* tell *which* data goes where: with proprietary modules you can only guess, trust their companies – or do a long-time screening (in the latter case you'd certainly have some surprises of what is transmitted without your telling so).¹

For crash reports, the two libraries I mentioned above are excellent FOSS solutions (as far as I've heard – I'm no Android dev myself). ACRA is already available a long time (its 5.2k stars here at Github should speak for it) and actively maintained, tracedroid is a bit younger and not that active (but I heard good mentions of it as well). Both are following "privacy first" – so they e.g. do not send any data before the user approves (Crashlytics and Firebase do it the other way around).

So TL;DR this would be a huge step privacy-wise, and you'd gain trust with us tin-foils :wink: If by dropping the two proprietary analytics modules the other two (GMS, Firebase) would become obsolete too and could be dropped, even more so – plus then your app could be made available at [F-Droid](https://f-droid.org/) (I gladly answer questions on that as well).

> would like to have some basic analytics

Similar field – but I'm afraid ACRA/tracedroid don't fit that bill. If "basic" is sufficient, there should be something FOSS-wise. Could you self-host a "light" server backend – and would that be an option for you (ideally with user opt-in, which could be obtained at first start, like a run-time permission)? If so, I'd try to find something for that and introduce it to you.

----

¹ <sub>note that each module you include with your app has access to everything your app has access to</sub>

**Comment by IzzySoft** [comment]
@msimonides any chance? I've meanwhile started notes what [acceptable analytics](https://gitlab.com/snippets/1896503#acceptable-analytics) I stumbled upon so far. List is definitely incomplete (suggestions welcome).

**Comment by IzzySoft** [comment]
I've just checked the latest release (0.9.1), and still find the trackers – which is a pity. Any chance for a F/LOSS build? Could certainly be done via a build flavor so you can keep the Google tracking in the Play Store variant while offering a "clean" version to those concerned.

**Comment by msimonides** [comment]
Yes, I look into releasing additional builds with no Firebase SDKs.

**Comment by IzzySoft** [comment]
That would be great! Please give me a ping here when such builds start to be released. Thanks a lot!

**Comment by msimonides** [comment]
I have just published version 0.9.4 - the APK here on GitHub should have Firebase SDKs removed.

**Comment by IzzySoft** [comment]
Wow! That's ele-phan-tastic! Not a single tracker left! :tada: :fireworks: Thanks a lot! My library scanner just confirmed it, so with today's sync there will be a new version available in my repo – and the Tracking AntiFeature removed. Yay \o/

**Comment by renarena** [comment]
https://github.com/renarena/aesopPlayer/pulls
msimonides already removed the tracker and homer is available in fdroid, so i thought, it could be possible for aesop player too.

**Comment by IzzySoft** [comment]
How does Aesop differ from Homer? Both look like they've seen no commits since 12/2020. Are both projects still maintained?

**Comment by DonnKey** [comment]
The two are similar (since Aesop is derived from Homer).  The major
differences are (1) details of the (user) UI, such as the ability to
control speed and volume with large gestures and not using any hardware
buttons and (2) support for adding/removing/tweaking (downloading) books
remotely without physical connection to a PC.  The latter allows remote
support of a user who is isolated or distant.  (COVID wasn't why that was
done, but it sure helps now that we're dealing with it.)  (3) Kiosk mode
usually (depending on the exact device) works well using just Application
Pinning (if you have it at all), rather than needing to be a device
controller.

It goes further with the QR install stuff so it's possible to install it as
a Full Kiosk Mode app but get automatic updates via Google Store.  (That
is, assuming you install on a freshly Factory-Reset device.)

It has its own website that covers all the details.

I haven't needed to do anything to Aesop since the last change, so I
haven't updated it.

DonnKey

**Comment by IzzySoft** [comment]
Thanks for the detailed explanation! So if you could make the APK available (ideally attached to its corresponding release), I could check if it fits into my repo. For F-Droid.org, same way as with Homer, you'd need to open an RFP there.

**Comment by renarena** [comment]
@IzzySoft: apk can be found there: https://github.com/DonnKey/aesopPlayer/releases/tag/v1.2.1

**Comment by IzzySoft** [comment]
Thanks! But sorry, no:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): Tracking

5 offenders.
```

I may close an eye on one or two (depending which ones), but five is too much.
