### ISSUE TITLE
The link to "Making a dedicated player" doesn't work

### ISSUE THREAD

**Issue by cubuspl42** [msimonides/homerplayer#24]
It's linked on https://msimonides.github.io/homerplayer/features.html and gives a 404 error. The problematic link is https://msimonides.github.io/install-dedicated.html

**Comment by cubuspl42** [comment]
I guess it should be https://msimonides.github.io/homerplayer/install-dedicated.html ?

**Comment by msimonides** [comment]
Thank you for letting me know, fixed.
